name: checks
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: go test ./params ./build ./core ./networks ./supervisor/committee ./supervisor/measure
      - run: go build ./...
      - run: python -m compileall experiments
